### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by caikan** [bajian/vue-toast#1]
很赞！能发布到 [npm](https://www.npmjs.com/) 和 [awesome-vue](https://github.com/vuejs/awesome-vue) 就更好了！

**Comment by bajian** [comment]
How to install from NPM

npm install vue-bajiantoast --save

install into Vue:
import Toast from 'vue-bajiantoast'
import 'vue-bajiantoast/dist/vue-bajiantoast.min.css'

Vue.use(Toast)
